### ISSUE TITLE
When will the miner program be available?

### ISSUE THREAD

**Issue by ccyanxyz** [vcashorg/vcash#1]
When are you going to release the miner program for vcash?

It seems for now I have to write my own miner to mine vcash.

**Comment by jdwldnqi837** [comment]
> When are you going to release the miner program for vcash?
> 
> It seems for now I have to write my own miner to mine vcash.

You can open the switch 'enable_stratum_server' in file '~/.vcash/main/vcash-server.toml', and set your btc-miner mining address as 'stratum_server_addr' to start mining. But as you can see VCash adopts Merged Mining method to mine coins alongside Bitcoin, so mining by btc-miner is not economically a good idea.
