### ISSUE TITLE
thread-heavy for vcash-wallet OWNERAPI invoking

### ISSUE THREAD

**Issue by ArayofEntropy** [vcashorg/vcash#10]
**Describe the bug**
While invoking the ownerapi of vcash-wallet,the thread of the ownerapi process keep increasing and 
finally cause OOM or unable to log into the VM.

**To Reproduce**
1. Run 'vcash-wallet owner_api'
2. Invoke the ownerapi per 10min after a while
3. `for prc in $(ps -A -o pid); do grep -s Threads /proc/${prc}/status | awk -v prc="${prc}" '{print prc, $2}'; done | sort -n -r -k 2 | head`
4. See the PID of thread-heavy  proccess should be ownerapi.

**Relevant Information**
-

**Screenshots**
-

**Desktop (please complete the following information):**
 - Ubuntu 16 
 - vcash-wallet  v.3.0.1

**Additional context**
-

**Comment by jdwldnqi837** [comment]
Thanks for your info.  Its fixed now and you can pull the latest code.
