### ISSUE TITLE
docker run tx-data issue?

### ISSUE THREAD

**Issue by bxlkm** [vcashorg/vcash#3]
Hi master:
    Vcash runs in docker. After mounting the directory, the following errors will occur. How should we solve them?
    20190708 06:07:30.456 INFO grin_servers::common::adapters - Received 32 block headers from 104.248.188.0:3514
20190708 06:07:30.473 INFO grin_servers::common::adapters - Received 32 block headers from 104.248.188.0:3514
20190708 06:07:30.574 INFO grin_servers::common::adapters - Received 32 block headers from 104.248.188.0:3514
20190708 06:07:30.593 INFO grin_servers::common::adapters - Received 32 block headers from 104.248.188.0:3514
20190708 06:07:30.613 INFO grin_servers::common::adapters - Received 32 block headers from 104.248.188.0:3514
20190708 06:07:30.630 INFO grin_servers::common::adapters - Received 32 block headers from 104.248.188.0:3514
20190708 06:07:30.646 INFO grin_servers::common::adapters - Received 32 block headers from 104.248.188.0:3514
20190708 06:07:30.660 INFO grin_servers::common::adapters - Received 32 block headers from 104.248.188.0:3514
20190708 06:07:30.674 INFO grin_servers::common::adapters - Received 19 block headers from 104.248.188.0:3514
20190708 06:07:59.214 ERROR grin_chain::txhashset::txhashset - hashset_replace fail on txhashset. err: Invalid cross-device link (os error 18)
20190708 06:07:59.220 ERROR grin_servers::common::adapters - Failed to save txhashset archive: TxHashSetErr: txhashset replacing fail 
 Cause: Unknown 
 Backtrace: 
20190708 06:07:59.226 ERROR grin_servers::grin::sync::state_sync - state_sync: error = Chain(Error { inner: 

TxHashSetErr: txhashset replacing fail }). restart fast sync
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)
20190708 06:08:05.867 ERROR grin_store::types - Corrupted storage, could not read an entry from data file: IOErr("failed to fill whole buffer", UnexpectedEof)

grin:
https://github.com/mimblewimble/grin/issues/2871

**Comment by jdwldnqi837** [comment]
you can try build from source code.
