### ISSUE TITLE
vcash2.0 and vcash-wallet2.0 release Interaction issues

### ISSUE THREAD

**Issue by bxlkm** [vcashorg/vcash#5]
hi everyone：
   please help me 

vcash2.0 wallet :

20190711 08:38:46.651 ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Request error: Cannot make request: an error occurred trying to connect: Connection refused (os error 111)
20190711 08:38:46.665 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 0.0.0.0:3515.
20190711 08:38:46.665 WARN grin_wallet_controller::controller - HTTP Foreign listener started.
20190711 08:43:23.579 ERROR grin_wallet_impls::node_clients::http - Unable to contact Node to get version info: Request error: Cannot make request: an error occurred trying to connect: Connection refused (os error 111)
20190711 08:43:23.582 WARN grin_wallet_controller::controller - Starting HTTP Foreign listener API server at 0.0.0.0:3515.
20190711 08:43:23.582 WARN grin_wallet_controller::controller - HTTP Foreign listener started.

**Comment by jdwldnqi837** [comment]
I can't reproduce this issue on version 2.0.0.
