### ISSUE TITLE
Vcash How to open rpc remote access port?

### ISSUE THREAD

**Issue by wangfucheng** [vcashorg/vcash#8]
Vcash How to open rpc remote access port?

**Comment by wangfucheng** [comment]
root@node-test:~/vcash# vcash
root@node-test:~/vcash# cat vcash-server.log

20190814 02:51:08.186 INFO grin_store::lmdb - Resized database from 1048576 to 134217728
20190814 02:51:08.251 ERROR grin_util::logger - 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Chain(Error { inner: 

Other Error: output vs rproof MMRs different sizes })': src/libcore/result.rs:997stack backtrace:
   0: grin_util::logger::send_panic_to_log::{{closure}}::hfc3b2cb8ab63bacc (0x55de1546dd20)
   1: rust_panic_with_hook (0x55de155a8b58)
             at src/libstd/panicking.rs:482
   2: continue_panic_fmt (0x55de155a85f1)
             at src/libstd/panicking.rs:385
   3: rust_begin_unwind (0x55de155a84d5)
   4: panic_fmt (0x55de155c2edc)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::hfd0274f43a036629 (0x55de14dcb238)
   6: vcash::cmd::server::start_server::h81794f5309322d6e (0x55de14dcc4d8)
   7: vcash::cmd::server::server_command::h69b279792a6cda1c (0x55de14dccdc5)
   8: vcash::real_main::h67fb1dfabbe4304b (0x55de14dfdec9)
   9: vcash::main::h771d5b05fc9bafb0 (0x55de14dfc9e5)
  10: std::rt::lang_start::{{closure}}::h5f24a0c7417635c6 (0x55de14dd86c2)
  11: {{closure}} (0x55de155a8472)
             at src/libstd/rt.rs:49
      do_call<closure,i32>
             at src/libstd/panicking.rs:297
  12: __rust_maybe_catch_panic (0x55de155aed19)
             at src/libpanic_unwind/lib.rs:87
  13: try<i32,closure> (0x55de155a8f7c)
             at src/libstd/panicking.rs:276
      catch_unwind<closure,i32>
             at src/libstd/panic.rs:388
      lang_start_internal
             at src/libstd/rt.rs:48
  14: main (0x55de14e01131)
  15: __libc_start_main (0x7f829c6ea09a)
  16: _start (0x55de14db94b8)
  17: <unknown> (0x0)

**Comment by jdwldnqi837** [comment]
try build from source.
