### ISSUE TITLE
payment issue

### ISSUE THREAD

**Issue by EircJC** [vcashorg/vcash#9]
当前钱包版本为3.0，
1、调用rpc支付接口init_send_tx时返回错误
"ClientCallback": "Posting transaction slate (is recipient listening?): Request error: Cannot make request: an IO error occurred: timed out"，
但是接收vcash的钱包是正常状态，端口监听正常

2、另一个钱包向外支付时log显示有大量错误导致支付失败
20191211 03:57:14.767 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 09146c487ce55c88889a2342b3ce0842295856736bc60bff19e8297b46ee194fe8 with error Not found.
20191211 03:57:14.767 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 09b92e9070361395edd35b0ddcca14ad90d948062d8f00eb37c5f2da08571d4c55 with error Not found.
20191211 03:57:14.767 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08ccdd9056971f8a0104aac38617f031491d030e2d7b6a63c61f3f0ab6501e8716 with error Not found.
20191211 03:57:14.767 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08eaf35c119cdc2fe27381f557c131e6433929283cbae81017b09bd428d0a9236e with error Not found.
20191211 03:57:14.767 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08285a1893019d6789e3c8592cf9c254efd1b40be65e7ca7623ec2a774fe46efdd with error Not found.
20191211 03:57:14.767 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 09941e1eb4c8182e82aa076371e55202c58b3227fa970b5d392805b4fa99bc1902 with error Not found.
20191211 03:57:14.767 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08ececdb6bc7d867bb86d8c9e291236f75d141a1ab4139492b99719c519c8b8c47 with error Not found.
20191211 03:57:14.767 ERROR grin_api::handlers::chain_api - Failure to get output for commitment 08afb104a66a4e300323e311cc714d4a5ba96e7ffe1d823dcda7465092d4222961 with error Not found.

3、钱包调用rpc查询等接口响应时间特别长，超过10s

**Comment by jdwldnqi837** [comment]
Are you sure is receiver wallet is really on listening mode? Actually wallet will initialize with a full chain scan if you lunch it first time, and that may take a while.

**Comment by EircJC** [comment]
使用 vcash_wallet send -d 发送可以成功，但是rpc会失败，现在返回错误为
"ClientCallback": "Posting transaction to node: Request error: Wrong response code: 500 Internal Server Error with data Body"

我的发送rpc为 
curl -0 -XPOST -u grin:`cat ~/.vcash/main/.api_secret` --data '{ "jsonrpc": "2.0", "method": "init_send_tx", "params": {"args":{"amount":'${send_amount}', "minimum_confirmations":0, "max_outputs":5, "num_change_outputs":2, "selection_strategy_is_use_all":false, "send_args": {"method":"http", "dest":"'${rec_address}'", "finalize":true, "post_tx":true, "fluff":false}}}, "id": 1}' http://127.0.0.1:3520/v2/owner

**Comment by jdwldnqi837** [comment]
I got some similar feedback. It should be a compatibility problem,  I'll fix this later.  Here is my suggestion for you right now:
```
cd  ~/.vcash/main/wallet_data
mv db db.back
mv saved_txs saved_txs.back
```
then initialize your wallet with info or scan command:
```
vcash-wallet info
```

**Comment by jdwldnqi837** [comment]
I'll close this issue. Pls feel free to let me know if any questions on this.
